### ISSUE TITLE
Assert fails on earley parser

### ISSUE THREAD

**Issue by uriva** [erezsh/lark#14]
Hi,
Should the assert in line 221 earley.py, in _compare_rules `assert rule1.origin == rule2.origin` ever fail?

Because it does :)

**Comment by erezsh** [comment]
Well, I can see how that might happen if _compare_drv calls itself recursively.

If you can provide an example in which it fails (grammar + input), I will be able to solve the issue.

**Comment by geographika** [comment]
Just managed to get this error myself whilst messing around with the mappyfile grammar (with Lark 0.2.7) - it may be of help to see why this could happen. 

Grammar change from https://github.com/geographika/mappyfile/blob/master/mappyfile/mapfile.g below:
```
composite: composite_type attr? _NL+ composite_body _END
       | composite_type points _END
       | composite_type pattern _END
       | composite_type attr _END
       | metadata
```
Attempting to parse:

```
    MAP
    METADATA 
        'wms_title' 'Test simple wms'
    END
    END
```


```
Traceback (most recent call last):
  File "D:\mappyfile\tests\test_snippets.py", line 545, in <module>
    test_metadata()
  File "D:\mappyfile\tests\test_snippets.py", line 133, in test_metadata
    assert(output(s) == exp)
  File "D:\mappyfile\tests\test_snippets.py", line 16, in output
    ast = p.parse(s)
  File ".\mappyfile\parser.py", line 70, in parse
    return self.g.parse(text+'\n')
  File "C:\VirtualEnvs\mappyfile\lib\site-packages\lark\lark.py", line 184, in parse
    return self.parser.parse(text)
  File "C:\VirtualEnvs\mappyfile\lib\site-packages\lark\parser_frontends.py", line 172, in parse
    return self.parser.parse(tokens)
  File "C:\VirtualEnvs\mappyfile\lib\site-packages\lark\parsers\earley.py", line 204, in parse
    ResolveAmbig().visit(tree)
  File "C:\VirtualEnvs\mappyfile\lib\site-packages\lark\tree.py", line 125, in visit
    getattr(self, subtree.data, self.__default__)(subtree)
  File "C:\VirtualEnvs\mappyfile\lib\site-packages\lark\parsers\earley.py", line 248, in _ambig
    best = min(tree.children, key=cmp_to_key(_compare_drv))
  File "C:\Python27\Lib\functools.py", line 87, in __lt__
    return mycmp(self.obj, other.obj) < 0
  File "C:\VirtualEnvs\mappyfile\lib\site-packages\lark\parsers\earley.py", line 239, in _compare_drv
    c = _compare_drv(t1, t2)
  File "C:\VirtualEnvs\mappyfile\lib\site-packages\lark\parsers\earley.py", line 239, in _compare_drv
    c = _compare_drv(t1, t2)
  File "C:\VirtualEnvs\mappyfile\lib\site-packages\lark\parsers\earley.py", line 233, in _compare_drv
    c = _compare_rules(tree1.rule, tree2.rule)
  File "C:\VirtualEnvs\mappyfile\lib\site-packages\lark\parsers\earley.py", line 223, in _compare_rules
    assert rule1.origin == rule2.origin
AssertionError
```

**Comment by geographika** [comment]
After investigating further it is due to a keyword matching two rules. In this case METADATA matches both _composite_item and composite. Removing from composite resolved the error for me. 

```
composite: composite_type attr? _NL+ composite_body _END
       | composite_type points _END
       | composite_type pattern _END
       | composite_type attr _END
	   | metadata
	   | validation

composite_body: _composite_item*
_composite_item: (composite|attr|points|projection|metadata|pattern|validation|values) _NL+
```

**Comment by erezsh** [comment]
Thank you for reporting this issue! It took me a while to track down.

To the best of my knowledge, this issue is now fixed in lark 0.2.8

If it recurs in any way, please re-open this issue.

**Comment by uriva** [comment]
Hi, this is still happening for me.
The grammar is:

```
  separator: "#"
  indexes: NUMBER? separator NUMBER

  from_time: "from_time" indexes
  to_time: "to_time" indexes
  time_range: from_time to_time

  from_day: "from_day" indexes
  to_day: "to_day" indexes
  day_range: from_day to_day

  day: "day" indexes
  day_enumeration: day+ | day day

  day_expression: day_enumeration  | day_range
  time_expression: from_time | to_time | time_range

  give_hours: day_expression time_expression
            | time_expression day_expression

  start: give_hours+

  %import common.NUMBER
  %import common.WS
  %ignore WS
```


And the input is:
> day1#0 from_time#0 to_time#0 day2#0 from_time#1 to_time1#1 day1#1 to_time2#1 day2#1 day1#2 day2#2

**Comment by erezsh** [comment]
Oops! My bad. Updated to 0.2.9 and it should work now. Hopefully this is the last of this issue :)

@uriva  Thanks for stress-testing my library, but I advise you to use a less-ambiguous grammar, or I imagine your users will be very confused.

**Comment by uriva** [comment]
Thank you Erez for this library, so far it seems to work really well.

As for ambiguity - right now I just get one parse, although the grammar is ambiguous. If I understand correctly, the library default just chooses the simplest parse tree. But soon I will want to prioritize some rules over others. Is there an easy way to do this, or I just need to look at the resulting trees and apply this logic myself?

**Comment by erezsh** [comment]
You're welcome @uriva !

Right now there is no easy way to tell lark how to prioritize the rules. But, I might add it if I have the time. When it becomes important, email me or open a new issue, and we will figure out a way to solve your problem.
