### ISSUE TITLE
Multiple sequential optional matches generate grammar errors

### ISSUE THREAD

**Issue by night199uk** [erezsh/lark#61]
Something like this:
```
HEXDIGIT: ("A" .. "F" ) | ("a" .. "f" ) | ("0" .. "9")
myhex4: HEXDIGIT? HEXDIGIT? HEXDIGIT? HEXDIGIT
```

Generates the error:
lark.common.GrammarError: Rule '<myhex4 : _HEXDIGIT _HEXDIGIT _HEXDIGIT>' already exists

It seems the rule generator doesn't discard sequential maybes of the same type; instead generating 3 variations of the 3 digit rule (for each option turned on or off). Dump from the rule generator:
```
<myhex4 : _HEXDIGIT _HEXDIGIT _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT>
```

Where you would expect:
```
<myhex4 : _HEXDIGIT _HEXDIGIT _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT _HEXDIGIT>
<myhex4 : _HEXDIGIT>
```

I was able to work around it by using a regular expression for now:
```
myhex4: /[a-fA-F0-9]{1,4}/
```

But does it make sense to have this work from a usability perspective?

**Comment by erezsh** [comment]
This ties to issue #60 
It should actually be fixed in `master`

**Comment by night199uk** [comment]
Just pulled master, looks to be still broken, slightly differently now:
```
myhex4: HEXDIGIT? HEXDIGIT? HEXDIGIT? HEXDIGIT
```

```
lark.common.GrammarError: Rule '<myhex4 : HEXDIGIT HEXDIGIT>' already exists
```

**Comment by erezsh** [comment]
Okay, it should work now (fetch from `master`)

**Comment by night199uk** [comment]
Thanks, works great!
